#!/usr/bin/env bash
set -e

if [[ ! -f Berksfile ]]; then
  cp /Berksfile.sample Berksfile
  trap 'rm -f Berksfile Berksfile.lock' EXIT SIGINT SIGTERM
  echo "Y29va2Jvb2sgJ2Rva2t1LXNpbXBsZScsIGdpdDogJ2h0dHBzOi8vZ2l0aHViLmNvbS9ybGlzdGVyL2NoZWYtZG9ra3Utc2ltcGxlLmdpdCcK" | base64 -d >> Berksfile
fi

[[ -d /root/.ssh_host ]] && cp -R /root/.ssh_host /root/.ssh && chown -R root /root/.ssh
PATH="/opt/chefdk/embedded/bin/:$PATH" LANG=C.UTF-8 /opt/chefdk/embedded/bin/bundle exec "$@"
